/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion;

/**
 *
 * @author esteb
 */
public class frm_Principal extends javax.swing.JFrame {

    /**
     * Creates new form frm_Principal
     */
    public frm_Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        Editar = new javax.swing.JMenu();
        agregar = new javax.swing.JMenuItem();
        menuEditarEvento = new javax.swing.JMenuItem();
        menuReservarEvento = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        MenuHabilitarAsientos = new javax.swing.JMenuItem();
        MenuComprarAsientos = new javax.swing.JMenuItem();
        menuModificarCompra = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Editar.setText("Eventos");

        agregar.setText("Agregar Evento");
        agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarActionPerformed(evt);
            }
        });
        Editar.add(agregar);

        menuEditarEvento.setText("Editar Evento");
        menuEditarEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEditarEventoActionPerformed(evt);
            }
        });
        Editar.add(menuEditarEvento);

        menuReservarEvento.setText("Reservar Evento");
        menuReservarEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuReservarEventoActionPerformed(evt);
            }
        });
        Editar.add(menuReservarEvento);

        jMenuItem4.setText("Editar Asiento");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        Editar.add(jMenuItem4);

        MenuHabilitarAsientos.setText("Habilitar Asientos");
        MenuHabilitarAsientos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuHabilitarAsientosActionPerformed(evt);
            }
        });
        Editar.add(MenuHabilitarAsientos);

        MenuComprarAsientos.setText("Venta Asientos");
        MenuComprarAsientos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuComprarAsientosActionPerformed(evt);
            }
        });
        Editar.add(MenuComprarAsientos);

        menuModificarCompra.setText("Modificar Venta");
        Editar.add(menuModificarCompra);

        jMenuBar1.add(Editar);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        frm_EditarAsientos e = new frm_EditarAsientos();
        e.setVisible(true);
        e.setLocationRelativeTo(null);

    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void MenuHabilitarAsientosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuHabilitarAsientosActionPerformed
        frm_Asientos a = new frm_Asientos();
        a.setVisible(true);
        a.setLocationRelativeTo(null);
    }//GEN-LAST:event_MenuHabilitarAsientosActionPerformed

    private void menuReservarEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuReservarEventoActionPerformed
        frm_VisualizarEvento fr = new frm_VisualizarEvento();
        fr.setVisible(true);
        fr.setLocationRelativeTo(null);
    }//GEN-LAST:event_menuReservarEventoActionPerformed

    private void menuEditarEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEditarEventoActionPerformed
        frm_EditarEvento fr = new frm_EditarEvento();
        fr.setVisible(true);
        fr.setLocationRelativeTo(null);
    }//GEN-LAST:event_menuEditarEventoActionPerformed

    private void agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarActionPerformed
        frm_AgregarEvento fr = new frm_AgregarEvento();
        fr.setVisible(true);
        fr.setLocationRelativeTo(null);
    }//GEN-LAST:event_agregarActionPerformed

    private void MenuComprarAsientosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuComprarAsientosActionPerformed
        frm_CompraAsientos fc = new frm_CompraAsientos();
        fc.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_MenuComprarAsientosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Editar;
    private javax.swing.JMenuItem MenuComprarAsientos;
    private javax.swing.JMenuItem MenuHabilitarAsientos;
    private javax.swing.JMenuItem agregar;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem menuEditarEvento;
    private javax.swing.JMenuItem menuModificarCompra;
    private javax.swing.JMenuItem menuReservarEvento;
    // End of variables declaration//GEN-END:variables
}
